server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
        - id: training-service
          uri: lb://training-service
          predicates:
            - Path=/api/training/**
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
