server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/media_service_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

cdn:
  base-url: ${CDN_BASE_URL:https://cdn.example.com}
