server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
